# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: dimitrius1011


  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  liquibase:
    enabled: true
    change-log: db/changelog/changelog.sql
# Server configuration
server:
  port: 8087 #set your port
  # Swagger configuration


